version: "3.9"
services:
    es:
      image: elasticsearch:7.8.1
      environment:
        - bootstrap.memory_lock=true
        - cluster.name=docker-cluster
        - cluster.routing.allocation.disk.threshold_enabled=false
        - discovery.type=single-node
        - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
      ulimits:
        memlock:
          hard: -1
          soft: -1
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      healthcheck:
        interval: 30s
        retries: 10
        test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    invest:
        build: .
        command: python /invest/manage.py runserver 0.0.0.0:443
        volumes:
          - .:/invest
        ports:
          - "443:443"
        env_file:
          - docker-compose.env
    kibana:
      image: kibana:7.6.2
      depends_on:
        es:
          condition: service_healthy
      environment:
        ELASTICSEARCH_URL: http://es:9200
        ELASTICSEARCH_HOSTS: http://es:9200
      ports:
        - 5601:5601
      healthcheck:
        interval: 30s
        retries: 20
        test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
networks:
  default:
    external: false
    name: docker-net

volumes:
  esdata:
    driver: local