version: "3.9"
services:
    es:
        image: elasticsearch:7.8.1
        environment:
          - discovery.type=single-node
        ports:
          - "9200:9200"
    invest:
        build: .
        command: python /invest/manage.py runserver 0.0.0.0:8080
        volumes:
          - .:/invest
        ports:
          - "8080:8080"
        env_file:
          - docker-compose.env