# Generated by Django 3.2.6 on 2021-09-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('long_name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(verbose_name='created')),
            ],
        )
    ]
