# Generated by Django 2.2.15 on 2021-08-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('long_name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
