# Generated by Django 2.2.15 on 2021-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
    ]
