# Generated by Django 3.2.6 on 2021-09-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210903_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stocks.stock'),
        ),
    ]
