# Generated by Django 3.2.6 on 2021-08-31 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210829_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.stock')),
            ],
        ),
    ]
