# Generated by Django 3.2.6 on 2021-09-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_datatick'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataTick',
            new_name='StockData',
        ),
    ]
